In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

In [3]:
body_df=pd.read_csv(data_url+"body_fat.csv", index_col="ID")

In [4]:
body_df.head()

     Sex   Age  Height  Weight  Body fat percentage
ID
F001   F  37.0   161.4    62.9                 32.8
F002   F  26.0   168.1    56.1                 31.5
F003   F  39.0   163.4    53.2                 25.2
F004   F  30.0   164.1    49.4                 21.8
F005   F  44.0   152.9    51.9                 24.2

In [5]:
pd.head(body_df)

AttributeError: module 'pandas' has no attribute 'head'

In [6]:
body_df.isna()

        Sex    Age  Height  Weight  Body fat percentage
ID
F001  False  False   False   False                False
F002  False  False   False   False                False
F003  False  False   False   False                False
F004  False  False   False   False                False
F005  False  False   False   False                False
...     ...    ...     ...     ...                  ...
M496  False  False   False   False                False
M497  False  False   False   False                False
M498  False  False   False   False                False
M499  False  False   False   False                False
M500  False  False   False   False                False

[1000 rows x 5 columns]

In [7]:
pd.isna(body_df)

        Sex    Age  Height  Weight  Body fat percentage
ID
F001  False  False   False   False                False
F002  False  False   False   False                False
F003  False  False   False   False                False
F004  False  False   False   False                False
F005  False  False   False   False                False
...     ...    ...     ...     ...                  ...
M496  False  False   False   False                False
M497  False  False   False   False                False
M498  False  False   False   False                False
M499  False  False   False   False                False
M500  False  False   False   False                False

[1000 rows x 5 columns]