In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.precision',6)

In [2]:
penguins=sns.load_dataset('penguins')

In [3]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [4]:
penguins.shape

(344, 7)

In [5]:
penguins.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='str')

In [6]:
penguins.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [7]:
penguins.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [ ]:
penguins.dropna(subset=['body_mass_g'], inplace=True)
#서브셋 지정하지 않은 상태로 하면 결측치 있는 샘플 싹 지움
#inplcae=False인 경우 새 데이터셋 생성

In [11]:
penguins.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  9
dtype: int64

In [12]:
training_columns=['bill_length_mm',
                  "bill_depth_mm",
                  "flipper_length_mm",
                  "body_mass_g",
                  "species"]

penguins_training=penguins[training_columns].copy()

In [13]:
penguins.info()

<class 'pandas.DataFrame'>
Index: 342 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            342 non-null    str
 1   island             342 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 21.4 KB

In [16]:
penguins_training["species"].value_counts(normalize=True).sort_index()

species
Adelie       0.441520
Chinstrap    0.198830
Gentoo       0.359649
Name: proportion, dtype: float64

In [15]:
penguins_training.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [21]:
X_bl=penguins_training.loc[:,"bill_length_mm"]
X_bl_Scaled=(X_bl-X_bl.mean())/X_bl.std()

In [24]:
X_bl_Scaled.describe()
#표준화하면 왜 성능 좋아지는지 물어보지마
#정규분포라는 가정하에 예측값을 구한다는 것 정도만 알아둬

count    3.420000e+02
mean     1.246566e-16
std      1.000000e+00
min     -2.165354e+00
25%     -8.603092e-01
50%      9.672352e-02
75%      8.385383e-01
max      2.871660e+00
Name: bill_length_mm, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_Scaled=scaler.fit_transform(penguins_training.iloc[:,:-1])
X_bl_Scaled=scaler.fit_transform(X_bl.values.reshape(-1,1))
#타겟은 표준화하지 않고 입력값으로 한다.
#해도 되지만 일반적으로 안함
#표준화를 먼저 한 다음에 훈련한다.
#표준화를 할 때 가까이 있는 특성들로
#훈련하는건 문제 없지만
#나중에 사람이 볼 수 있게?

In [ ]:
X_train_Scaled.describe()
#어레이로 반환되기 때문에 데이터 프레임으로 변경하고 뭐 하고 해야지..ㅇㅇ

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [31]:
X_bl_Scaled

array([[-0.88449874],
       [-0.81112573],
       [-0.66437972],
       [-1.32473679],
       [-0.84781224],
       [-0.92118525],
       [-0.86615549],
       [-1.80166135],
       [-0.35254443],
       [-1.12296102],
       [-1.12296102],
       [-0.5176337 ],
       [-0.976215  ],
       [-1.70994508],
       [-1.34308004],
       [-0.95787175],
       [-0.26082817],
       [-1.74663159],
       [ 0.38118565],
       [-1.12296102],
       [-1.14130427],
       [-1.47148281],
       [-1.04958801],
       [-0.9395285 ],
       [-1.58154232],
       [-0.60934996],
       [-0.62769321],
       [-1.10461777],
       [-0.62769321],
       [-0.81112573],
       [-1.23302053],
       [-0.81112573],
       [-0.5543202 ],
       [-1.37976655],
       [-0.86615549],
       [-0.9395285 ],
       [-0.31585793],
       [-1.15964752],
       [-0.75609598],
       [-1.3614233 ],
       [-0.57266346],
       [-1.45313956],
       [ 0.03266386],
       [-1.26970704],
       [-0.79278248],
       [-0.5176337 ],
       [-1.17799078],
       [-1.45313956],
       [-0.29751468],
       [-0.79278248],
       [-0.70106622],
       [-1.63657208],
       [-0.35254443],
       [-1.72828834],
       [-0.46260394],
       [-0.90284199],
       [-0.60934996],
       [-1.3614233 ],
       [-1.15964752],
       [-1.50816931],
       [-0.4809472 ],
       [-1.15964752],
       [-0.5176337 ],
       [-1.37976655],
       [-0.42591744],
       [-1.54485582],
       [-0.5176337 ],
       [-1.47148281],
       [-0.38923094],
       [-1.91172086],
       [-0.77443923],
       [-0.79278248],
       [ 0.34449915],
       [-1.54485582],
       [-0.20579842],
       [-0.5543202 ],
       [-1.23302053],
       [-1.41645305],
       [-0.33420118],
       [-1.70994508],
       [-0.18745516],
       [-1.32473679],
       [-1.61822882],
       [-1.21467728],
       [-0.4809472 ],
       [-1.3981098 ],
       [-1.28805029],
       [-1.03124476],
       [-0.92118525],
       [-1.50816931],
       [-0.5176337 ],
       [-1.8200046 ],
       [-0.79278248],
       [-1.41645305],
       [-0.57266346],
       [-1.06793126],
       [-0.66437972],
       [-1.98509387],
       [-0.13242541],
       [-1.63657208],
       [-0.53597695],
       [-1.14130427],
       [-1.12296102],
       [-1.10461777],
       [-0.77443923],
       [-0.976215  ],
       [-1.04958801],
       [-1.06793126],
       [-0.13242541],
       [-1.06793126],
       [ 0.30781264],
       [-0.77443923],
       [-0.31585793],
       [-0.79278248],
       [-0.22414167],
       [-0.976215  ],
       [-1.21467728],
       [-1.50816931],
       [-0.5176337 ],
       [-1.41645305],
       [-1.14130427],
       [-0.68272297],
       [-0.46260394],
       [-1.59988557],
       [-0.60934996],
       [-0.9395285 ],
       [-0.44426069],
       [-0.90284199],
       [ 0.03266386],
       [-0.99455825],
       [-0.15076866],
       [-1.30639354],
       [-1.17799078],
       [-1.06793126],
       [-0.5176337 ],
       [-1.52651256],
       [-0.68272297],
       [-1.26970704],
       [-0.77443923],
       [-0.68272297],
       [-0.60934996],
       [-2.16852639],
       [-0.59100671],
       [-1.21467728],
       [-0.90284199],
       [-0.86615549],
       [-1.34308004],
       [-1.45313956],
       [-1.12296102],
       [-1.45313956],
       [-0.44426069],
       [ 0.47290191],
       [ 1.11491573],
       [ 1.35337801],
       [ 0.27112614],
       [ 1.61018354],
       [ 0.23443963],
       [ 0.3995289 ],
       [ 1.35337801],
       [ 0.38118565],
       [ 1.35337801],
       [ 0.49124516],
       [ 1.42675102],
       [ 0.56461817],
       [ 1.48178077],
       [ 0.3628424 ],
       [ 1.20663199],
       [ 1.16994549],
       [ 2.5823759 ],
       [ 0.45455866],
       [ 0.96816972],
       [-0.27917142],
       [ 0.83976695],
       [-0.13242541],
       [ 1.22497525],
       [ 0.50958841],
       [ 1.48178077],
       [ 1.20663199],
       [ 1.02319947],
       [ 0.45455866],
       [ 1.62852679],
       [-0.5543202 ],
       [ 1.88533232],
       [-0.26082817],
       [ 1.29834825],
       [ 1.05988598],
       [ 0.65633443],
       [ 0.67467768],
       [ 1.48178077],
       [ 0.54627492],
       [ 1.75692956],
       [ 0.93148321],
       [ 0.41787215],
       [ 1.280005  ],
       [ 0.28946939],
       [ 1.280005  ],
       [ 1.26166175],
       [ 1.13325898],
       [ 0.93148321],
       [ 1.39006451],
       [ 1.07822923],
       [ 0.76639394],
       [ 1.37172126],
       [ 0.32615589],
       [ 1.2433185 ],
       [-0.26082817],
       [ 1.51846728],
       [ 0.23443963],
       [ 0.98651297],
       [ 1.15160224],
       [ 0.30781264],
       [ 1.46343752],
       [ 0.52793167],
       [ 0.32615589],
       [ 2.17882435],
       [-0.07739565],
       [ 1.04154272],
       [ 1.26166175],
       [ 1.15160224],
       [ 0.3995289 ],
       [ 1.11491573],
       [ 0.87645346],
       [ 1.11491573],
       [ 0.67467768],
       [ 0.47290191],
       [ 0.27112614],
       [ 0.50958841],
       [-0.11408216],
       [ 0.52793167],
       [-0.5543202 ],
       [ 0.93148321],
       [ 0.28946939],
       [ 0.8214237 ],
       [ 0.34449915],
       [ 0.98651297],
       [-0.35254443],
       [ 0.96816972],
       [ 0.41787215],
       [ 0.87645346],
       [ 1.15160224],
       [ 0.21609638],
       [ 0.47290191],
       [ 0.43621541],
       [-0.18745516],
       [ 0.3995289 ],
       [ 0.10603687],
       [ 0.71136419],
       [ 0.7847372 ],
       [ 1.11491573],
       [ 0.61964793],
       [-0.20579842],
       [ 0.21609638],
       [ 2.87586793],
       [ 0.94982646],
       [ 0.8214237 ],
       [-0.24248492],
       [ 0.08769362],
       [ 0.01432061],
       [ 0.87645346],
       [-0.22414167],
       [ 1.04154272],
       [ 0.25278289],
       [ 1.04154272],
       [ 1.20663199],
       [-0.0590524 ],
       [ 0.28946939],
       [ 1.20663199],
       [ 0.17940988],
       [ 0.23443963],
       [ 0.49124516],
       [ 0.83976695],
       [ 0.21609638],
       [ 1.13325898],
       [ 0.47290191],
       [ 0.19775313],
       [-0.0223659 ],
       [ 0.28946939],
       [-0.13242541],
       [ 1.18828874],
       [ 0.25278289],
       [ 0.41787215],
       [ 0.32615589],
       [ 1.90367557],
       [ 0.34449915],
       [ 1.07822923],
       [ 0.41787215],
       [ 1.02319947],
       [-0.07739565],
       [ 1.2433185 ],
       [ 0.69302094],
       [ 0.45455866],
       [ 0.7847372 ],
       [ 0.47290191],
       [ 0.45455866],
       [ 0.8581102 ],
       [ 0.65633443],
       [ 1.31669151],
       [ 0.23443963],
       [ 0.23443963],
       [ 0.94982646],
       [ 1.57349703],
       [ 0.63799118],
       [ 1.11491573],
       [ 0.17940988],
       [ 1.26166175],
       [-0.0957389 ],
       [ 1.35337801],
       [ 0.65633443],
       [ 1.50012403],
       [ 0.65633443],
       [ 1.51846728],
       [ 0.28946939],
       [ 1.02319947],
       [ 0.10603687],
       [ 1.26166175],
       [ 1.00485622],
       [ 0.54627492],
       [ 0.8214237 ],
       [ 1.31669151],
       [ 0.83976695],
       [ 2.1971676 ],
       [ 0.60130468],
       [ 0.94982646],
       [ 0.61964793],
       [ 0.52793167],
       [-0.40757419],
       [ 1.7385863 ],
       [-0.11408216],
       [ 0.76639394],
       [ 1.20663199],
       [ 1.07822923],
       [-0.07739565],
       [ 1.39006451],
       [ 0.41787215],
       [ 2.05042159],
       [ 0.10603687],
       [ 0.89479671],
       [ 0.60130468],
       [ 0.52793167],
       [ 1.18828874],
       [ 0.23443963],
       [ 1.09657248]])